# Generated by Django 2.0.2 on 2018-04-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_type_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="geonames_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="GeoNamesId"),
        ),
    ]
