# Generated by Django 2.0.2 on 2018-05-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_place_geonames_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_reference",
            field=models.ManyToManyField(
                blank=True,
                related_name="file_reference",
                to="maps.Reference",
                verbose_name="references",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="super",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub",
                to="maps.Reference",
                verbose_name="has super",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="scan_reference",
            field=models.ManyToManyField(
                blank=True,
                related_name="scan_reference",
                to="maps.Reference",
                verbose_name="references",
            ),
        ),
    ]
