from django.urls import path

from .views import (
    index,
    browse,
    changelog,
    files,
    imprint,
    institute,
    leaflet,
    map,
    network,
    person,
    place,
    reference,
    search,
    team,
    type,
)

app_name = "maps"

urlpatterns = [
    path("changelog/", changelog.index, name="changelog"),
    path("imprint/", imprint.index, name="imprint"),
    path("search/", search.index, name="search"),
    path("index/", index.index, name="index"),
    path("network/", network.index, name="network"),
    path("team/", team.index, name="team"),
    path("leaflet/", leaflet.index, name="leaflet"),
    path("leaflet/base-map-info/", leaflet.base_map_info, name="base-map-info"),
    path("leaflet/detail/(?P<id_>\d+)/", leaflet.detail, name="leaflet-detail"),
    path("browse/", browse.index, name="browse"),
    path("browse/view/(?P<pk>\d+)/", browse.view, name="browse-view"),
    path("map/", map.index, name="map"),
    path("map/detail/(?P<pk>\d+)/", map.detail, name="map-detail"),
    path("map/create/", map.Create.as_view(), name="map-create"),
    path("map/update/(?P<pk>\d+)/", map.Update.as_view(), name="map-update"),
    path("map/delete/(?P<pk>\d+)/", map.Delete.as_view(), name="map-delete"),
    path("reference/", reference.index, name="reference"),
    path("reference/detail/(?P<pk>\d+)/", reference.detail, name="reference-detail"),
    path("reference/create/", reference.Create.as_view(), name="reference-create"),
    path(
        "reference/update/(?P<pk>\d+)/",
        reference.Update.as_view(),
        name="reference-update",
    ),
    path(
        "reference/delete/(?P<pk>\d+)/",
        reference.Delete.as_view(),
        name="reference-delete",
    ),
    path("person/", person.index, name="person"),
    path("person/detail/(?P<pk>\d+)/", person.detail, name="person-detail"),
    path("person/create/", person.Create.as_view(), name="person-create"),
    path("person/update/(?P<pk>\d+)/", person.Update.as_view(), name="person-update"),
    path("person/delete/(?P<pk>\d+)/", person.Delete.as_view(), name="person-delete"),
    path("institute/", institute.index, name="institute"),
    path("institute/detail/(?P<pk>\d+)/", institute.detail, name="institute-detail"),
    path("institute/create/", institute.Create.as_view(), name="institute-create"),
    path(
        "institute/update/(?P<pk>\d+)/",
        institute.Update.as_view(),
        name="institute-update",
    ),
    path(
        "institute/delete/(?P<pk>\d+)/",
        institute.Delete.as_view(),
        name="institute-delete",
    ),
    path("place/", place.index, name="place"),
    path("place/detail/(?P<pk>\d+)/", place.detail, name="place-detail"),
    path("place/create/", place.Create.as_view(), name="place-create"),
    path("place/update/(?P<pk>\d+)/", place.Update.as_view(), name="place-update"),
    path("place/delete/(?P<pk>\d+)/", place.Delete.as_view(), name="place-delete"),
    path("type/", type.index, name="type"),
    path("type/detail/(?P<pk>\d+)/", type.detail, name="type-detail"),
    path("type/create/(?P<pk>\d+)/", type.create, name="type-create"),
    path("type/update/(?P<pk>\d+)/", type.Update.as_view(), name="type-update"),
    path("type/delete/(?P<pk>\d+)/", type.Delete.as_view(), name="type-delete"),
    path("files/", files.index, name="files-index"),
    path("files/file-detail/(?P<pk>\d+)/", files.file_detail, name="file-detail"),
    path("files/scan-detail/(?P<pk>\d+)/", files.scan_detail, name="scan-detail"),
    path("files/file-create/", files.FileCreate.as_view(), name="file-create"),
    path(
        "files/file-create/(?P<class_name>.+)/(?P<origin_id>\d+)/",
        files.FileCreate.as_view(),
        name="file-create",
    ),
    path("files/scan-create/", files.ScanCreate.as_view(), name="scan-create"),
    path(
        "files/scan-create/(?P<class_name>.+)/(?P<origin_id>\d+)/",
        files.ScanCreate.as_view(),
        name="scan-create",
    ),
    path(
        "files/file-update/(?P<pk>\d+)/",
        files.FileUpdate.as_view(),
        name="file-update",
    ),
    path(
        "files/scan-update/(?P<pk>\d+)/",
        files.ScanUpdate.as_view(),
        name="scan-update",
    ),
    path(
        "files/file-delete/(?P<pk>\d+)/",
        files.FileDelete.as_view(),
        name="file-delete",
    ),
    path(
        "files/scan-delete/(?P<pk>\d+)/",
        files.ScanDelete.as_view(),
        name="scan-delete",
    ),
    path(
        "files/delete-orphaned-files/",
        files.delete_orphaned_files,
        name="delete-orphaned-files",
    ),
]

handler404 = "webpage.views.handler404"
